### PR TITLE
Correct the casing of acadYear in getUserDetails query

### PR DESCRIPTION
**Pull request by soumitradev**

### CODE REVIEW

**Review by majimearun — APPROVED** [review]

**Review by majimearun — COMMENTED** [review]
Why are some snake case and others camel though

**Comment by soumitradev** [comment]
amogus, looks like they're not being fetched either then

**Review by majimearun — CHANGES_REQUESTED** [review]
Make sure all of them are being retrieved

**Review by majimearun — APPROVED** [review]
Everything is being fetched now, LGTM

**Pull request merged**
