### PR TITLE
[BREAKING] Rework repo to move to latest Node LTS, replace ESLint with BiomeJS, bump deps, add frontend code

### PR DESCRIPTION
**Pull request by soumitradev**
Setup frontend code, reorganize repo to accommodate frontend, bump deps and node versions to LTS, rewrite parts of Docker containers to move to new versions, and replace ESLint entirely with BiomeJS.

This will most definitely break existing dev, staging and prod environments, though the last 2 should need only minor adjustments to the server's nginx configuration to accommodate for the new frontend.

I hope to document the things that break dev environments extensively in the README. **DO NOT MERGE** until these things are added to README.

Due to the size of this PR I recommend we skip review for this PR, and instead work off of confirmations of individual dev environments working, instead of a comprehensive review of the entire code.

### CODE REVIEW

**Comment by soumitradev** [comment]
As of f0b4322, these changes have now been documented in the README. I will now verify if people can read and understand the README and setup the dev environment correctly, after which this PR can be merged.

**Comment by Anurav-Garg** [comment]
Confirmed that dev environment setup was successful following the instructions in the README. Took a while but that's probably my internet.

**Review by JustAGhost23 — COMMENTED** [review]
Confirmed that dev environment setup was successful following the instructions in the README.

**Comment by skoriop** [comment]
Confirmed that dev environment works after following the `README`.

**Comment by soumitradev** [comment]
As people were able to set it up, I'm merging, since the instructions seem clear enough now.

**Pull request merged**
