### PR TITLE
Add frontend prod container

### PR DESCRIPTION
**Pull request by soumitradev**
`NGINX_PORT` is now used both in prod and dev, `FRONTEND_PORT` is now `FRONTEND_DEV_PORT` to make its role clearer

### CODE REVIEW

**Comment by soumitradev** [comment]
Another build only PR, I recommend this be merged if people can manage to get the prod container running and verify that all the dev stuff is working in prod.

**Review by skoriop — COMMENTED** [review]
I think we need to check `NODE_ENV` to conditionally render debugging components (for Tanstack Router). 

Otherwise, LGTM.

**Review by skoriop — APPROVED** [review]
LGTM

**Review by skoriop — CHANGES_REQUESTED** [review]
image
Files outside of `frontend/src/` aren't getting copied to the docker container.

**Review by majimearun — APPROVED** [review]
Builds and runs fine

**Review by majimearun — APPROVED** [review]

**Pull request merged**
